# This file generates the GitHub Actions matrix
---
include:
  - board: nrfmicro_13
    shield: sweeple_dongle dongle_display
    artifact-name: sweeple_dongle
  - board: nice_nano_v2
    shield: sweeple_left
    artifact-name: sweeple_left
  - board: nice_nano_v2
    shield: sweeple_right
    artifact-name: sweeple_right

  # reset
  - board: nrfmicro_13
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset