# This file generates the GitHub Actions matrix
---
include:
  - board: nrfmicro_13
    shield: sweeple_central_dongle dongle_display
    artifact-name: sweeple_central_dongle
  - board: nice_nano_v2
    shield: sweeple_central_left
    artifact-name: sweeple_central_left
  - board: nice_nano_v2
    shield: sweeple_peripheral_left
    artifact-name: sweeple_peripheral_left
  - board: nice_nano_v2
    shield: sweeple_peripheral_right
    artifact-name: sweeple_peripheral_right
    
  - board: nice_nano_v2
    shield: sweeple_central_left
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: sweeple_central_left_with_logging

  # reset
  - board: nrfmicro_13
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset