# This file generates the GitHub Actions matrix
---
include:
  - board: nrfmicro_13
    shield: sweeple_central_dongle dongle_display
    artifact-name: sweeple_central_dongle
  - board: nice_nano_v2
    shield: sweeple_peripheral_left
    artifact-name: sweeple_peripheral_left
  - board: nice_nano_v2
    shield: sweeple_peripheral_right
    artifact-name: sweeple_peripheral_right

  # reset
  - board: nrfmicro_13
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset